// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package protos;

public final class packetProto {
  private packetProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\"\236\001\n\006Packet\022\n\n\002id\030\010 \001(\005\022\014\n" +
      "\004type\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022\023\n\013sequenceNum" +
      "\030\003 \001(\005\022\020\n\010checksum\030\004 \001(\t\022\020\n\010fileName\030\005 \001" +
      "(\t\022\017\n\007swarmId\030\006 \001(\005\022\014\n\004data\030\007 \001(\014\022\024\n\014hos" +
      "tLocation\030\t \001(\tB\027\n\006protosB\013packetProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "Id", "Type", "Size", "SequenceNum", "Checksum", "FileName", "SwarmId", "Data", "HostLocation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
